### ISSUE TITLE
please use curl wrapper

### ISSUE THREAD

**Issue by danmarsden** [edu-sharing/moodle-atto_edusharing#3]
https://github.com/edu-sharing/plugin-moodle-edu-sharing-atto-editor/blob/master/preview.php#L58

please don't call curl directly - use moodle's internal curl wrapper. Many web servers will sit behind a proxy and the internal curl wrapper deals with that.

**Comment by ernst-metaventis** [comment]
switched to moodle's internal curl wrapper.
