### ISSUE TITLE
string concatenation in lang pack

### ISSUE THREAD

**Issue by danmarsden** [edu-sharing/moodle-atto_edusharing#8]
string concatentaion in the lang packs is not allowed - it causes problems for the Moodle translation tool

eg:
$string['test'] = "sometext"."somemoretext";
or
$string['test'] = "sometext".$string['someotheritem'];

each string must be contained within one set of quotes eg:
$string['test'] = "sometext somemoretext";

**Comment by ernst-metaventis** [comment]
fixed
